### ISSUE TITLE
Comece a planejar

### ISSUE THREAD

**Issue by lucasrmagalhaes** [lucasrmagalhaes/homework-issues#785]
**Todo projeto de SEO precisa de um bom planejamento estratégico onde são traçados e definidos os objetivos da ação. Esses objetivos vão além de conseguir mais visitantes para o seu site, eles também precisam visar o foco principal do seu produto ou serviço: ligações, cadastros, venda direta etc. Sabendo disso, analise as alternativas a seguir e marque a única correta.**

- [ ] Para um bom e completo planejamento estratégico, o primeiro passo é iniciar a pesquisa de palavras-chave para incluir no conteúdo textual do site.

- [ ] Para um bom e completo planejamento estratégico, o primeiro passo é criar um site atrativo, responsivo e moderno, usando cores que contrastem bem e facilitem a leitura do usuário.

- [x] Para um bom e completo planejamento estratégico, o primeiro passo é documentar todas as informações necessárias e pertinentes ao projeto: dados da empresa, do produto ou serviço, público-alvo, preço, concorrentes etc. Esse documento leva o nome de briefing.

> _O primeiro passo para começar o planejamento estratégico de SEO é um bom e completo Briefing! É a partir dele que você identifica os objetivos e levanta ideias para o seu conteúdo. Sem um briefing, fica bem mais difícil acertar!_
